// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBTnpsh9zVJr9fEZjAFnDR38ZzVI6zR7JA",
    authDomain: "taskify-c4cc7.firebaseapp.com",
    databaseURL: "https://taskify-c4cc7-default-rtdb.firebaseio.com",
    projectId: "taskify-c4cc7",
    storageBucket: "taskify-c4cc7.appspot.com",
    messagingSenderId: "319737304688",
    appId: "1:319737304688:web:709b95b0dacac8a564c6b5",
    measurementId: "G-GBF2E8KVL3"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaMO_y2VtkQmL_Ll5lp8u6P7-eNA0aDqg',
    appId: '1:319737304688:android:848aeb22fdf5fffd64c6b5',
    messagingSenderId: '319737304688',
    projectId: 'taskify-c4cc7',
    storageBucket: 'taskify-c4cc7.appspot.com',
  );


  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVYTMZSfsCJ2txEI3GCggqQe0JIRXcnqU',
    appId: '1:319737304688:ios:164eefa06384511264c6b5',
    messagingSenderId: '319737304688',
    projectId: 'webtaskify',
    storageBucket: 'taskify-c4cc7.appspot.com',
    iosClientId: '319737304688-6cujd7a5uo0p5sd82sbujjapqkj311g7.apps.googleusercontent.com',
    iosBundleId: 'com.leonferdian.taskify.taskify',
  );
}
